///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MakTech
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddOneUser recording.
    /// </summary>
    [TestModule("65f355d9-0c7b-4820-9e50-ae101231e4b7", ModuleType.Recording, 1)]
    public partial class AddOneUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MakTechRepository repository.
        /// </summary>
        public static MakTechRepository repo = MakTechRepository.Instance;

        static AddOneUser instance = new AddOneUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddOneUser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddOneUser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyApp.FirstName' at Center.", repo.MyApp.FirstNameInfo, new RecordItemIndex(0));
            repo.MyApp.FirstName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Jay' with focus on 'MyApp.FirstName'.", repo.MyApp.FirstNameInfo, new RecordItemIndex(1));
            repo.MyApp.FirstName.PressKeys("Jay");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyApp.LastName' at Center.", repo.MyApp.LastNameInfo, new RecordItemIndex(2));
            repo.MyApp.LastName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Branham' with focus on 'MyApp.LastName'.", repo.MyApp.LastNameInfo, new RecordItemIndex(3));
            repo.MyApp.LastName.PressKeys("Branham");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyApp.Movie' at Center.", repo.MyApp.MovieInfo, new RecordItemIndex(4));
            repo.MyApp.Movie.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyApp.Gender' at Center.", repo.MyApp.GenderInfo, new RecordItemIndex(5));
            repo.MyApp.Gender.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyApp.InputTagAdd' at Center.", repo.MyApp.InputTagAddInfo, new RecordItemIndex(6));
            repo.MyApp.InputTagAdd.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
